[features]
resolution = true
skip-lint = false

[programs.localnet]
zesty = "EFGd7a5WYMCwPb2ayfKq6JeavNmaicuMTFfLif8VeU3M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.29.0"
